// <auto-generated />
using Lara.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lara.Migrations
{
    [DbContext(typeof(DBContexto))]
    [Migration("20201108014227_Primeiro_Migration")]
    partial class Primeiro_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Lara.Model.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdPessoa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apelido")
                        .HasColumnName("Apelido")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoCivil")
                        .HasColumnName("EstadoCivil")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Idade")
                        .HasColumnName("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnName("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sexo")
                        .HasColumnName("Sexo")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPessoa");

                    b.ToTable("bpm_pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
